site_name: HouLixiang Blog
site_author: 侯理想
theme:
  name: material
  
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-2
        name: Switch to dark mode
      primary: green
      accent: blue

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: pink
      accent: blue
  features:
    - content.code.copy
  icon: 
    repo: fontawesome/brands/github #右上角图标
edit_uri: edit/main/docs # 编辑按钮跳转的链接 
repo_url: https://github.com/WangYuanze111 # 右上角点击跳转的链接
repo_name: WangYuanze111.github # 右上角的名字

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/WangYuanze111
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/MaelOmbdQYHxu2c
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/457805155?spm_id_from=333.1007.0.0
    - icon: fontawesome/solid/paper-plane
      link: mailto:<wangyuanze.hlx@gmail.com> #联系方式
  analytics:
    provider: google
    property: G-KJB4RXSKZG
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - 前言: "index.md"
  - 读书笔记:
      - 《光变》 :
          - 第一章 北京电子管厂的兴衰: "第一章：北京电子管厂的兴衰.md"
  - 新建: "New.md"
  - 第二页: "page2.md"
  - 大工作业: "大连理工大学C语言.md"